Fix inconsistency between new implementation of PD and old T2* weighting removal method
hMRI-group/hMRI-toolbox pull request #98
Opened 2024-04-29 15:40 UTC by lukeje

Fix #87

2024-06-13 09:45 UTC, Barisevrenugur requested changes
different tests consistently return the following error:
```
-------- R2* map calculation (basic exponential decay) --------

INFO: minimum number of echoes required for R2* map calculation is 4.
Number of PDw echoes available: 8

	-------- Reading and averaging the images --------
12-Jun-2024 19:16:50 - Failed  'Create hMRI maps'
Error using inv
Too many input arguments.
In file "/tmp/hmri_naivetest_ugurcan/329533/spm12/toolbox/hMRI-cbs/hmri_read_vols.m" (???), function "hmri_read_vols" at line 43.
In file "/tmp/hmri_naivetest_ugurcan/329533/spm12/toolbox/hMRI-cbs/hmri_create_MTProt.m" (???), function "hmri_create_MTProt" at line 222.
In file "/tmp/hmri_naivetest_ugurcan/329533/spm12/toolbox/hMRI-cbs/hmri_run_create.m" (???), function "hmri_create_local" at line 132.
In file "/tmp/hmri_naivetest_ugurcan/329533/spm12/toolbox/hMRI-cbs/hmri_run_create.m" (???), function "hmri_run_create" at line 21.

The following modules did not run:
Failed: Create hMRI maps
```

2024-06-13 12:09 UTC, lukeje commented on hmri_create_MTProt.m
> +% ensure amount of data matches number of echoes
I tried to keep all of these checks together with the ones that were there before. I think moving them could break other things...

2024-06-13 12:09 UTC, lukeje commented
> different tests consistently return the following error:
> ...

Should be fixed now.

2025-09-22 09:16 UTC, Barisevrenugur submitted a review, later dismissed
currently  267 commits behind from the current  master with merge conflicts in MTprot: resolve merge conflicts and merge master into this PR. 

P.S. The following (non-tested) helper-PR, that I have been keeping on the side for sync,  can be used for support purposes if needed:

https://github.com/hMRI-group/hMRI-toolbox/tree/MergeMasterINTOfix_87_nr_echoes_forA

2025-09-22 14:10 UTC, lukeje commented
@Barisevrenugur I rebased the changes on the current master. The error maps were what caused the merge conflict.

2025-10-07 21:22 UTC, Barisevrenugur commented
Review and DIFFing against the back up sync:

https://github.com/hMRI-group/hMRI-toolbox/tree/MergeMasterINTOfix_87_nr_echoes_forA

revealed that one of the commits from the following bugfix:

https://github.com/hMRI-group/hMRI-toolbox/pull/113

partially dissepeared, during rebasing to the current master. I commited the fix which syncronizes (related part of) this PR back to:

https://github.com/hMRI-group/hMRI-toolbox/pull/113

Now, this PR and the back up sync is the same.  



> @Barisevrenugur I rebased the changes on the current master. The error maps were what caused the merge conflict.

2025-10-08 15:37 UTC, lukeje commented
Weird... thanks for fixing it, Baris.

2025-10-13 16:08 UTC, ChristophePhillips approved these changes
Looks good to me.

2025-10-14 09:06 UTC, antoinelutti reviewed
I think it looks good. 
Just one thing: I've noticed considerations about the number of echoes for averaging that seem to appear quite late in the code (lines 1420-1426). I found this surprising as the PD, T1s, A,... calculation is done previously.

2025-10-14 09:06 UTC, antoinelutti commented on hmri_create_MTProt.m
> +% find maximum echo time common to all available contrasts
Does it make sense to have considerations on the number of echoes for averaging this late in the code @lukeje (lines 1420-1426)? The calculation of PDw, T1w, A... is done higher up

2025-10-14 09:13 UTC, lukeje commented on hmri_create_MTProt.m
> +% find maximum echo time common to all available contrasts
Input checking like this is in a separate function at the bottom of the file called `get_mpm_params`, which is called before any calculations. That's why it appears to come after the calculations, though it actually run before.

2025-10-14 09:19 UTC, antoinelutti approved these changes

2025-11-10 12:20 UTC, Barisevrenugur commented
Hi @siawoosh , have you reviewed this PR yet- what do you think, does it check out to you too?

2026-04-21 10:11 UTC, lukeje commented
Closing as changes are already in beta v1.0.0 branch.

2026-04-21 10:11 UTC, closed without merging